version: '3.7'

services:
  db:
    image: postgres:13.2
    volumes:
      - ./docker/db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    expose:
      - 5432
    environment:
      - POSTGRES_DB=co2_emission
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    # ports:
    #   - 5432:5432
    restart: unless-stopped

  backend:
    build: .
    container_name: backend
    ports:
      - 8000:8000
    restart: always