"""empty message

Revision ID: 396595ee9afa
Revises: 74a4382f25e7
Create Date: 2023-03-30 11:31:54.414357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396595ee9afa'
down_revision = '74a4382f25e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folklift_master_data', sa.Column('fuel_efficiency', sa.Float(), nullable=True))
    op.add_column('folklift_master_data', sa.Column('fuel_type', sa.String(), nullable=True))
    op.add_column('folklift_master_data', sa.Column('units', sa.String(), nullable=True))
    op.drop_column('folklift_master_data', 'forklift_year')
    op.drop_column('folklift_master_data', 'forklift_make')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folklift_master_data', sa.Column('forklift_make', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('folklift_master_data', sa.Column('forklift_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('folklift_master_data', 'units')
    op.drop_column('folklift_master_data', 'fuel_type')
    op.drop_column('folklift_master_data', 'fuel_efficiency')
    # ### end Alembic commands ###
