"""empty message

Revision ID: 74a4382f25e7
Revises: 8db4539706f6
Create Date: 2023-03-29 21:36:46.613563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a4382f25e7'
down_revision = '8db4539706f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trans_activity', sa.Column('transportation_master_data_id', sa.Integer(), nullable=True))
    op.drop_constraint('trans_activity_company_facility_master_data_id_fkey', 'trans_activity', type_='foreignkey')
    op.create_foreign_key(None, 'trans_activity', 'transportation_master_data', ['transportation_master_data_id'], ['id'])
    op.drop_column('trans_activity', 'company_facility_master_data_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trans_activity', sa.Column('company_facility_master_data_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trans_activity', type_='foreignkey')
    op.create_foreign_key('trans_activity_company_facility_master_data_id_fkey', 'trans_activity', 'company_facility_master_data', ['company_facility_master_data_id'], ['id'])
    op.drop_column('trans_activity', 'transportation_master_data_id')
    # ### end Alembic commands ###
