"""empty message

Revision ID: 8db4539706f6
Revises: 3942c0671d2c
Create Date: 2023-03-29 20:50:36.776033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db4539706f6'
down_revision = '3942c0671d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transportation_master_data', 'vehicle_fuel_source_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transportation_master_data', sa.Column('vehicle_fuel_source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
