"""empty message

Revision ID: a8aff69a0a06
Revises: dec0638abe86
Create Date: 2023-04-28 11:10:29.803851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8aff69a0a06'
down_revision = 'dec0638abe86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
