"""empty message

Revision ID: dec0638abe86
Revises: 396595ee9afa
Create Date: 2023-03-30 15:17:35.040369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec0638abe86'
down_revision = '396595ee9afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facility_activity', sa.Column('date', sa.String(), nullable=True))
    op.add_column('trans_activity', sa.Column('date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trans_activity', 'date')
    op.drop_column('facility_activity', 'date')
    # ### end Alembic commands ###
